name: Wake Up Supabase

on:
  schedule:
    - cron: '0 0 * * 1,3,5'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping to Supabase API
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
          -I
